# Minimal uv package manager config (uv chosen as package manager)
[project]
name = "noumenal"
requires-python = ">=3.14"

[uv]
package-manager = "uv"
# Add uv-managed dependencies here when you install packages with uv
